########################################################################################################################
#
# Library: GenericKit
#
# Copyright (C) 2026~Present ChengXueWen.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
########################################################################################################################

# Policy settings for commands defined by GenericKit. These will also be injected into the top level policy scope of each
# GenericKit module when building GenericKit so that modules have the same policy settings as GenericKit by default.
# They can be overridden by individual GenericKit modules in their own .cmake.conf files if needed.
#
# NOTE: These two values are also hard-coded in GKITBuildInternalsConfig.cmake because that file is used in-place by a
#       superbuild, so there is no opportunity for substituting the values from here. Keep both locations in sync.
set(GKIT_MIN_NEW_POLICY_CMAKE_VERSION 3.22)
set(GKIT_MAX_NEW_POLICY_CMAKE_VERSION 3.31)

set(CMAKE_POLICY_VERSION_MINIMUM 3.22)

cmake_policy(SET CMP0075 NEW) # use CMAKE_REQUIRED_LIBRARIES
cmake_policy(SET CMP0083 NEW) # use check_pie_supported
cmake_policy(SET CMP0091 NEW) # use CMAKE_MSVC_RUNTIME_LIBRARY